// <auto-generated />
using System;
using DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbContext.Migrations.SqlServerDbContext
{
    [DbContext(typeof(MainDbContext.SqlServerDbContext))]
    partial class SqlServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttractionDbM", b =>
                {
                    b.Property<Guid>("AttractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttractionCategory")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AttractionDescription")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("AttractionName")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("CityDbMCityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("AttractionId");

                    b.HasIndex("CityDbMCityId");

                    b.ToTable("Attractions");
                });

            modelBuilder.Entity("CityDbM", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("CountryDbMCountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CityId");

                    b.HasIndex("CountryDbMCountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CountryDbM", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("ReviewDbM", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttractionDbMAttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttractionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewComment")
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ReviewRating")
                        .HasColumnType("int");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReviewId");

                    b.HasIndex("AttractionDbMAttractionId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UserDbM", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Seeded")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(200)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AttractionDbM", b =>
                {
                    b.HasOne("CityDbM", "CityDbM")
                        .WithMany("AttractionDbMs")
                        .HasForeignKey("CityDbMCityId");

                    b.Navigation("CityDbM");
                });

            modelBuilder.Entity("CityDbM", b =>
                {
                    b.HasOne("CountryDbM", "CountryDbM")
                        .WithMany("CityDbMs")
                        .HasForeignKey("CountryDbMCountryId");

                    b.Navigation("CountryDbM");
                });

            modelBuilder.Entity("ReviewDbM", b =>
                {
                    b.HasOne("AttractionDbM", "AttractionDbM")
                        .WithMany("ReviewDbMs")
                        .HasForeignKey("AttractionDbMAttractionId");

                    b.HasOne("UserDbM", "UserDbM")
                        .WithMany("ReviewDbMs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttractionDbM");

                    b.Navigation("UserDbM");
                });

            modelBuilder.Entity("AttractionDbM", b =>
                {
                    b.Navigation("ReviewDbMs");
                });

            modelBuilder.Entity("CityDbM", b =>
                {
                    b.Navigation("AttractionDbMs");
                });

            modelBuilder.Entity("CountryDbM", b =>
                {
                    b.Navigation("CityDbMs");
                });

            modelBuilder.Entity("UserDbM", b =>
                {
                    b.Navigation("ReviewDbMs");
                });
#pragma warning restore 612, 618
        }
    }
}
